In [1]:
import numpy as np

In [2]:
np.array([10,27,6,9])

array([10, 27,  6,  9])

In [3]:
a = np.array([10,27,6,9])

In [4]:
type(a)

numpy.ndarray

In [5]:
np.array([2.47,3,7,6.1])  #numpy array sabit tipli olmaya zorlar tam sayıları çıktı da ondalık olarak gösterir.

array([2.47, 3.  , 7.  , 6.1 ])

In [6]:
np.array([2.47,3,7,6.1], dtype='float32') 

array([2.47, 3.  , 7.  , 6.1 ], dtype=float32)

In [7]:
np.zeros(8, dtype=int)   #sıfırlardan oluşan array

array([0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones(10)              #birlerden oluşur

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.full((3,5),9)         #3x5 lik 9 sayısından oluşan matris oluşur 

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [13]:
np.arange(0,15,2, dtype = None)       #fonksiyonun ilk parmtsi başlangıç sayı, 2. parmt bitiş sayısı dahil değildir, 3. parmt si adım sayısı, 4. parmt si tip belirleme için 

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [14]:
np.linspace(0,3,15)

array([0.        , 0.21428571, 0.42857143, 0.64285714, 0.85714286,
       1.07142857, 1.28571429, 1.5       , 1.71428571, 1.92857143,
       2.14285714, 2.35714286, 2.57142857, 2.78571429, 3.        ])

In [15]:
np.linspace(0,3,15)       #iki değer arasında belirli sayıda değerler oluşturulur

array([0.        , 0.21428571, 0.42857143, 0.64285714, 0.85714286,
       1.07142857, 1.28571429, 1.5       , 1.71428571, 1.92857143,
       2.14285714, 2.35714286, 2.57142857, 2.78571429, 3.        ])

In [16]:
np.random.normal(1,2,(4,5))

array([[ 1.37139561,  0.84127714,  1.29840179,  0.8059942 ,  2.54855119],
       [-1.2180823 , -0.71435674,  1.67000685,  2.65114169, -0.41814554],
       [ 2.37559117,  2.73386264,  4.11025889, -1.58578478,  2.58955384],
       [ 0.59332763, -3.31985983, -1.51111414,  5.13356227,  1.21325023]])

In [17]:
np.random.randint(2,20,(4,5))

array([[ 9,  5,  4,  8,  6],
       [18, 11,  2,  9,  8],
       [ 9,  7, 13, 10, 15],
       [19, 10, 11,  8, 19]])