In [1]:
import numpy as np

In [4]:
x = np.random.randint(15, size = 15)

In [5]:
x[0]        #array in ilk değeri

0

In [6]:
x

array([ 0,  9,  5,  6,  7,  1,  4,  6,  0,  6, 14,  5,  1,  5, 14])

In [8]:
x[-1]       #array in son değeri 

14

In [10]:
x[-2]       #array sondan ikinci değeri

5

In [11]:
x[-2]=8     #sondan ikinci değere yeni değeri kolay bir şekilde atanır

In [12]:
x

array([ 0,  9,  5,  6,  7,  1,  4,  6,  0,  6, 14,  5,  1,  8, 14])

In [13]:
y = np.random.randint(15, size = (3,4))

In [14]:
y

array([[ 8,  0,  9,  5],
       [ 4,  4,  2,  1],
       [12,  5, 11, 13]])

In [17]:
y[0,0]       #ilk değer satır, ikinci değer sütun

8

In [18]:
y[2,1]

5

In [19]:
y[2,1] = 19  #değer değiştirelim

In [20]:
y[2,1]

19

In [26]:
x[ :8]

array([0, 9, 5, 6, 7, 1, 4, 6])

# matrix

In [27]:
list = [[10,20,30],[20,30,40],[40,50,60]]

In [28]:
matrixDizi= np.array(list)

In [29]:
matrixDizi

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [34]:
matrixDizi[0]      #ilk satır

array([10, 20, 30])

In [37]:
matrixDizi[1][2]   #1. satır ve 2. sütun kesişiminde olan sayı

40

In [38]:
matrixDizi[1,2]    #daha basit kullanımı

40

In [39]:
matrixDizi[1: ,2]  #birinci satır dan itibaren ikinci sütun da ki değerler

array([40, 60])

In [40]:
matrixDizi[0: ,1]  

array([20, 30, 50])

In [41]:
yeniList = [[0,1,2,3,4],[5,6,7,8,9,],[10,11,12,13,14],[1,16,17,18,19],[20,21,22,23,24]]

In [43]:
yeniMatrix = np.array(yeniList)

In [44]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 1, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
yeniMatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])