In [3]:
import numpy as np

In [4]:
np.arange(1,16)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
np.arange(1,16).reshape((3,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [10]:
a = np.array([2,3,4])    # a bir vektör

In [14]:
b = a.reshape((1,3))     #a vektörünü 1x3 lük matrise dönüştürüyoruz

In [15]:
a.ndim   # a değişkenin boyutu

1

In [16]:
b.ndim   #b değişkenin boyutu

2

* neden tek boyutlu array i matris e dönüştürmemiz gerek? 
* fonksiyonların bizden beklediği 2 boyutlu array olabilir. bu yüzden vektör görünümlü olan array i fonksiyon için matris e dönüştürmemiz gerekebilir.

In [17]:
a[np.newaxis,:]    #a tek boyutlu array newaxis ile 2 boyutlu olarak yazdırılır

array([[2, 3, 4]])

In [18]:
a[:,np.newaxis]    #2 boyutlu olarak sütun şeklinde yazdırılır

array([[2],
       [3],
       [4]])