In [1]:
import numpy as np

In [2]:
a = [1,3,9,15,62,78,87,124]

In [3]:
a

[1, 3, 9, 15, 62, 78, 87, 124]

In [4]:
np.split(a,[3,7])               #a değişkenini 3. dizi elemanından ve 7. elemandan kesip 3 parçaya ayrılır

[array([1, 3, 9]), array([15, 62, 78, 87]), array([124])]

In [5]:
a1,a2,a3 = np.split(a,[3,7])   #ayrılan arrayler değişkenlere atanır.

In [6]:
a1

array([1, 3, 9])

In [7]:
a2

array([15, 62, 78, 87])

In [8]:
a3

array([124])

In [9]:
x = np.arange(16).reshape((4,4))

In [10]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
np.vsplit(x,[2])         #2 indeks den itibaren ayırır

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [12]:
x1,x2 = np.vsplit(x,[2]) 

In [13]:
x1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [14]:
x2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
x3,x4 = np.hsplit(x,[2])

In [19]:
x3

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [20]:
x4

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])