In [2]:
import numpy as np

In [3]:
newArray = np.random.randint(1,100,20)   # 1 ile 100 değerler arasında rastgele 20 değer döndür

In [4]:
newArray

array([56, 69, 19, 47, 40, 66, 55, 77, 72, 64, 67, 84, 11, 66, 15, 24, 99,
       72, 10,  2])

In [5]:
newArray > 19

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
       False, False])

In [6]:
sonuc = newArray >19

In [7]:
sonuc

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
       False, False])

In [8]:
newArray

array([56, 69, 19, 47, 40, 66, 55, 77, 72, 64, 67, 84, 11, 66, 15, 24, 99,
       72, 10,  2])

In [10]:
newArray[sonuc]        #24 den büyük değerleri alıyor(sadece true değerleri)

array([56, 69, 47, 40, 66, 55, 77, 72, 64, 67, 84, 66, 24, 99, 72])

In [11]:
sonDizi = np.arange(0,24)

In [12]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [14]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [15]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [17]:
sonDizi / sonDizi    # sıfırı sıfıra bölerken hata kodu verebilir

<ipython-input-17-10f3100bdc8d>:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi / sonDizi    # sıfırı sıfıra bölerken hata kodu verebilir


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [19]:
np.sqrt(sonDizi)     #değerlerin karekökü alınır

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [20]:
np.max(sonDizi)

23

In [21]:
np.min(sonDizi)

0