In [1]:
import numpy as np

In [2]:
x = np.array([1,3,5])
y = np.array([2,4,6])

In [3]:
np.concatenate([x,y])        # iki array  uç uca eklendi

array([1, 3, 5, 2, 4, 6])

In [4]:
a = np.array([[1,2,3],[4,5,6]])   #2 boyutlu array

In [5]:
np.concatenate([a,a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [9]:
a = np.array([[1,2,3,],[4,5,6]])
b = np.array([7,8,9])

In [10]:
a.ndim

2

In [11]:
b.ndim

1

In [19]:
np.vstack([a,b])      #boyut uyuşmazlığından dolayı birleşimi hata  almamak için vstack kullanırız.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
c = np.array([[12],[13]])

In [21]:
c.shape

(2, 1)

In [22]:
a.shape

(2, 3)

In [23]:
np.hstack([a,c])   #boyut uyuşmazlığından dolayı birleşimi hata  almamak için hstack kullanırız.

array([[ 1,  2,  3, 12],
       [ 4,  5,  6, 13]])